name: Generate SBOM and VEX

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Trivy CLI
        uses: aquasecurity/trivy-action@v0.59.0

      - name: Generate CycloneDX SBOM
        run: |
          trivy fs \
            --format cyclonedx \
            --output sbom.cdx.json \
            .

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx
          path: sbom.cdx.json

      - name: Generate CycloneDX VEX from SBOM
        run: |
          trivy sbom \
            sbom.cdx.json \
            --vex sbom.vex.cdx

      - name: Upload VEX artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-vex
          path: sbom.vex.cdx
