name: Generate SBOM & VEX

on:
  push:
    branches: [main]

jobs:
  sbom-and-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install cve-bin-tool jq
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh |
            sh -s -- -b /usr/local/bin

      - name: Create CycloneDX SBOM (1.6)
        run: |
          syft . \
            -o cyclonedx-json \
            --file sbom.cdx.json \
            --cyclone-dx-schema-version 1.6

      - name: Normalize metadata.tools
        run: |
          jq '.metadata.tools = (.metadata.tools.components | map({ name: .name, version: .version }))' \
            sbom.cdx.json > sbom.cdx.patched.json

      - name: Generate VEX
        run: |
          cve-bin-tool \
            --sbom cyclonedx \
            --sbom-file sbom.cdx.patched.json \
            --vex-type cyclonedx \
            --vex-output sbom.vex.json \
            --vendor "${{ github.repository_owner }}" \
            --product "${{ github.event.repository.name }}" \
            --release "${{ github.sha }}" \
            || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.patched.json
            sbom.vex.json
