name: SBOM + VEX (combined)

on:
  push:
    branches: [ main ]

jobs:
  sbom-and-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM with embedded vulnerabilities
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          scanners: vuln
          output: sbom-vex.cdx.json

      - name: Upload combined SBOM+VEX artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-vex
          path: sbom-vex.cdx.json
