name: Generate SBOM and VEX

on:
  push:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for package.json
        id: check_package_json
        run: |
          if [ -f "package.json" ]; then
            echo "has_package_json=true" >> $GITHUB_OUTPUT
          else
            echo "has_package_json=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for pom.xml
        id: check_pom_xml
        run: |
          if [ -f "pom.xml" ]; then
            echo "has_pom_xml=true" >> $GITHUB_OUTPUT
          else
            echo "has_pom_xml=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check_package_json.outputs.has_package_json == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: steps.check_package_json.outputs.has_package_json == 'true'
        run: npm ci

      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0.17.9
        with:
          path: .
          output-file: sbom.spdx.json

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install CVE Binary Tool
        run: pip install "cve-bin-tool==3.4.*"

      - name: Generate CycloneDX VEX from SPDX SBOM
        run: |
          cve-bin-tool \
            --sbom spdx \
            --sbom-file sbom.spdx.json \
            --vex-type cyclonedx \
            --vex-output sbom.vex.json \
            --vendor ${{ github.repository_owner }} \
            --product ${{ github.event.repository.name }} \
            --release ${{ github.sha }}

      - name: Upload VEX artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-vex
          path: sbom.vex.json
