name: Generate SBOM + VEX

on:
  push:
    branches:
      - main

jobs:
  sbom-and-vex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.cdx.json
      - run: trivy sbom sbom.cdx.json --vex sbom.vex.cdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.json
            sbom.vex.cdx.json
