name: SBOM + Auto‑Generated VEX

on:
  push:
    branches: [ main ]

jobs:
  sbom-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate CycloneDX SBOM
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.cdx.json

      - name: Scan for vulnerabilities (JSON)
        run: |
          trivy fs --format json --output vuln.json . 
        # Trivy can output JSON for filesystem scans with --format json :contentReference[oaicite:0]{index=0}

      - name: Auto‑generate VEX from scan results
        run: |
          jq '{
            bomFormat:       "CycloneDX",
            specVersion:     "1.5",
            version:        1,
            vulnerabilities: [
              (.Results[].Vulnerabilities[] | {
                id:       .VulnerabilityID,
                analysis: {
                  state:         "under_investigation",
                  justification: "auto-generated by CI"
                },
                affects: [{ ref: .PkgRef }]
              })
            ]
          }' vuln.json > sbom.vex.cdx.json
        # We turn each vulnerability record into a CycloneDX VEX entry

      - name: Upload SBOM + VEX artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.json
            sbom.vex.cdx.json
