name: SBOM + VEX Generation

on:
  push:
    branches:
      - main

jobs:
  sbom-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4                                       

      - name: Install Trivy CLI
        uses: aquasecurity/setup-trivy@v0.2.3                            
      - name: Generate CycloneDX SBOM
        run: trivy sbom --format cyclonedx --output sbom.cdx.json       

      - name: Generate SBOM + VEX embedded
        run: trivy sbom --format cyclonedx --scanners vuln \
               --output sbom-vex.cdx.json                              

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4                                
        with:
          name: sbom-vex
          path: |
            sbom.cdx.json
            sbom-vex.cdx.json
