name: Generate SBOM & VEX

on:
  push:
    branches:
      - main

jobs:
  sbom-and-vex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Install cve-bin-tool
        run: pip install cve-bin-tool

      - name: Generate CycloneDX SBOM
        run: syft . -o cyclonedx-json --file sbom.cdx.json

      - name: Patch metadata.tools for CycloneDX compliance
        run: |
          jq '
            .metadata.tools = (
              .metadata.tools.components
              | map({
                  vendor: .author,
                  name:   .name,
                  version:.version
                })
            )
          ' sbom.cdx.json > sbom.cdx.patched.json

      - name: Generate VEX document
        run: |
          cve-bin-tool \
            --sbom cyclonedx \
            --sbom-file sbom.cdx.patched.json \
            --vex-type cyclonedx \
            --vex-output sbom.vex.json \
            --vendor "${{ github.repository_owner }}" \
            --product "${{ github.event.repository.name }}" \
            --release "${{ github.sha }}" \
            || true
