name: Generate SBOM & VEX

on:
  push:
    branches:
      - main

jobs:
  sbom-vex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Install Vexy
        run: pip install vexy

      - name: Generate CycloneDX SBOM
        run: syft . -o cyclonedx-json --file sbom.cdx.json

      - name: Patch metadata.tools for Vexy
        run: |
          jq '
            .metadata.tools = (
              .metadata.tools.components
              | map({
                  vendor: .author,
                  name:   .name,
                  version:.version
                })
            )
          ' sbom.cdx.json > sbom.cdx.patched.json

      - name: Create Vexy config
        run: |
          cat <<EOF > vexy.yml
          sources:
            osv:
          EOF

      - name: Patch OSV schema enum to include 1.6.0
        run: |
          MODEL_PATH=$(python3 -c "import osv, os; print(os.path.join(os.path.dirname(osv.__file__), 'model.py'))")
          sed -i '/v1_5_0 = "1.5.0"/a \    v1_6_0 = "1.6.0"' "$MODEL_PATH"

      - name: Generate VEX document
        run: |
          vexy \
            --config vexy.yml \
            --in-file sbom.cdx.patched.json \
            --format json \
            --output sbom.vex.json

      - name: Upload SBOM & VEX artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.patched.json
            sbom.vex.json
