name: Generate SBOM + VEX

on:
  push:
    branches:
      - main

jobs:
  sbom-and-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SBOM in CycloneDX format
        uses: aquasecurity/trivy-action@v0.13.0
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.cdx.json

      - name: Generate VEX from SBOM
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            aquasec/trivy:latest sbom sbom.cdx.json --vex sbom.vex.cdx.json

      - name: Upload SBOM and VEX artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.json
            sbom.vex.cdx.json
