name: Generate SBOM and VEX

on:
  push:
    branches:
      - main

jobs:
  sbom-vex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Vexy
        run: pip install vexy

      - name: Generate CycloneDX SBOM
        run: syft . -o cyclonedx-json > sbom.cdx.json :contentReference[oaicite:0]{index=0}

      - name: Create Vexy config
        run: |
          cat <<EOF > vexy.yml
          sources:
            osv:
          EOF

      - name: Generate VEX
        run: vexy --config vexy.yml --in-file sbom.cdx.json --format json --output sbom.vex.json :contentReference[oaicite:1]{index=1}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.json
            sbom.vex.json
