name: Generate SBOM & VEX

on:
  push:
    branches: [main]

jobs:
  sbom-and-vex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and tools
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq curl
          pip install cve-bin-tool
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        shell: bash

      - name: Generate CycloneDX SBOM
        run: |
          syft . -o cyclonedx-json --file sbom.cdx.json
        shell: bash

      - name: Patch SBOM specVersion to 1.6
        run: |
          jq '.specVersion = "1.6"' sbom.cdx.json > sbom.cdx.patched.json
        shell: bash

      - name: Generate VEX document
        run: |
          cve-bin-tool \
            --sbom cyclonedx \
            --sbom-file sbom.cdx.patched.json \
            --vex-type cyclonedx \
            --vex-output sbom.vex.json \
            --vendor "${{ github.repository_owner }}" \
            --product "${{ github.event.repository.name }}" \
            --release "${{ github.sha }}" || true
        shell: bash

      - name: Upload SBOM & VEX artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-vex
          path: |
            sbom.cdx.patched.json
            sbom.vex.json
